CREATE DATABASE DATABASEADONET

USE DATABASEADONET

CREATE TABLE Studets(
ID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(550) NOT NULL,
Surname VARCHAR(550) NOT NULL,
Age INT CHECK(Age BETWEEN 12 AND 65) NOT NULL);